/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Polygon;

/**
 *
 * @author Alienware
 */
public class DienteGUI extends javax.swing.JPanel {

  //Declaramos variables
        
        //Poligono arriba externo
        private int poli1X[] = {1, 40, 30, 12};
        private int poli1Y[] = {1, 1, 12, 12};
        //Poligono arriba interno
        private int poli1IX[] = {10, 30, 26, 14};
        private int poli1IY[] = {4, 4, 8, 8};
        //Poligono izquierda externo
        private int poli2X[] = {1, 1, 12, 12};
        private int poli2Y[] = {1, 40, 28, 12};
          //Poligono izquierda interno
        private int poli2IX[] = {4, 4, 9, 9};
        private int poli2IY[] = {8, 32, 26, 14};
        //Poligono derecha externo
        private int poli3X[] = {40, 40, 30, 30};
        private int poli3Y[] = {1, 40, 28, 12};
        //Poligono derecha interno
        private int poli3IX[] = {38, 38, 33, 33};
        private int poli3IY[] = {7, 34, 26, 14};        
        //Poligono abajo externo
        private int poli4X[] = {1, 40, 30, 12};
        private int poli4Y[] = {40, 40, 28, 28};
        //Poligono abajo interno
        private int poli4IX[] = {8, 35, 28, 14};
        private int poli4IY[] = {37, 37, 32, 32};
        //Poligono medio interno
        private int poli5IX[] = {15, 28, 28, 15};
        private int poli5IY[] = {15, 15, 26, 26};
        
        
        private Polygon poli1;	//Polígono de la clase Polygon
        private Polygon poli1I;	//Polígono de la clase Polygon
        private Polygon poli2;	//Polígono de la clase Polygon
        private Polygon poli2I;	//Polígono de la clase Polygon
        private Polygon poli3;	//Polígono de la clase Polygon
        private Polygon poli3I;	//Polígono de la clase Polygon
        private Polygon poli4;	//Polígono de la clase Polygon
        private Polygon poli4I;	//Polígono de la clase Polygon
        private Polygon poli5I;	//Polígono de la clase Polygon
        
        private int []  bandera = {0,0,0,0,0};
        
    public DienteGUI() {
        initComponents();
        //Crea un polígono con 4 vértices
                this.bandera = bandera;
                poli1 = new Polygon(poli1X, poli1Y, 4);
                poli1I = new Polygon(poli1IX, poli1IY, 4);
                poli2 = new Polygon(poli2X, poli2Y, 4);
                poli2I = new Polygon(poli2IX, poli2IY, 4);
                poli3 = new Polygon(poli3X, poli3Y, 4);
                poli3I = new Polygon(poli3IX, poli3IY, 4);
                poli4 = new Polygon(poli4X, poli4Y, 4);
                poli4I = new Polygon(poli4IX, poli4IY, 4);
                poli5I = new Polygon(poli5IX, poli5IY, 4);
                //Tamaño del JFrame
                setSize(40,40);
                //Hace visible el JFrame en la pantalla
                setVisible(true);
    }
    
    public int [] getBandera(){
        return this.bandera;
    }
    
    public void setBandera(int[] bandera)
    {
        this.bandera=bandera;
    }
    
    public void paint(Graphics g) {
               
                g.setColor(Color.WHITE);	//Color Blanco
                //Rellena el fondo de color Blanco
                g.fillRect(0, 0, getWidth(), getHeight());
                g.setColor(Color.black);	//Color Rojo
                //Dibuja un polígono rojo
                g.drawPolygon(poli1);
                g.drawPolygon(poli2);
                g.drawPolygon(poli3);
                g.drawPolygon(poli4);
                g.setColor(Color.darkGray);
                
                if(bandera[0]==1)
                {
                    g.drawPolygon(poli1I);
                    g.fillPolygon(poli1I);
                }
                if(bandera[1]==1)
                {
                    g.drawPolygon(poli2I);
                    g.fillPolygon(poli2I);
                }
                if(bandera[2]==1)
                {
                    g.fillPolygon(poli3I);
                    g.fillPolygon(poli3I);
                }
                if(bandera[3]==1)
                {
                    g.fillPolygon(poli4I);
                    g.fillPolygon(poli4I);
                }
                if(bandera[4]==1)
                {
                    g.fillPolygon(poli5I);
                    g.fillPolygon(poli5I);
                }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(42, 55));
        setMinimumSize(new java.awt.Dimension(42, 55));
        setPreferredSize(new java.awt.Dimension(42, 55));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
