/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DP.Diente;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Alienware
 */
public class Odontograma extends javax.swing.JFrame {

    private String codigoHistoriaClinica;
    private ArrayList<Diente> dientes = new ArrayList<Diente>();  
    
    
    public Odontograma() {   
            initComponents();
            System.out.println(this.codigoHistoriaClinica);
            int [] aux = {0,0,0,0,0}; 
            Diente [] indiceDientes = {new Diente(),new Diente(),new Diente(),new Diente(),new Diente(),new Diente(),new Diente(),new Diente()};
            String [] parte1 = {"18","17","16","15","14","13","12","11"};
            try {
                dientes = (new Diente("05033378180123456789").consultarDientes());
             } catch (ClassNotFoundException ex) {
                Logger.getLogger(Odontograma.class.getName()).log(Level.SEVERE, null, ex);
             }
                
            for(int i= 0; i<indiceDientes.length;i++)
            {
                for(int j=0;j<dientes.size();j++)
                {
                    if(dientes.get(j).getIndiceDiente().equals(parte1[i]))
                            indiceDientes[i] = dientes.get(j);
                }
            }
                //JPanel [] paneles1 = {fila1,fila2,fila3,fila4};
                DienteGUI [] dientesGUI = {new DienteGUI(),new DienteGUI(),new DienteGUI(),new DienteGUI(),new DienteGUI(),new DienteGUI(),new DienteGUI(),new DienteGUI()};
                for(int i =0; i<4;i++)
                {
                    //System.out.println(indiceDientes[i].getIndiceDiente());
                        aux[0] = indiceDientes[i].getCaraA();
                        aux[1] = indiceDientes[i].getCaraB();
                        aux[2] = indiceDientes[i].getCaraC();
                        aux[3] = indiceDientes[i].getCaraD();
                        aux[4] = indiceDientes[i].getCaraE();
                    //System.out.println(aux[0]+""+aux[1]+""+aux[2]+""+aux[3]+""+aux[4]);         
                    dientesGUI[i].setBandera(aux);
                    int [] bandera = dientesGUI[i].getBandera();
                    System.out.println(bandera[0]+""+bandera[1]+""+bandera[2]+""+bandera[3]+""+bandera[4]);
                    
                    this.getContentPane().add(dientesGUI[i]);
                    dientesGUI[i].repaint();
                    /*paneles1[i].repaint();
                    paneles1[i].add(dientesGUI[i]);*/
                }
                /*
                for(int i = 0; i<10;i++)
                {
                    DienteGUI piezaTMP = new DienteGUI(aux);
                    fila2.add(piezaTMP);
                }
                for(int i = 0; i<10;i++)
                {
                    DienteGUI piezaTMP = new DienteGUI(aux);
                    fila3.add(piezaTMP);
                }
                for(int i = 0; i<16;i++)
                {
                    DienteGUI piezaTMP = new DienteGUI(aux);   
                    fila4.add(piezaTMP);
                }*/
       
      
        
    }
    
    public void setCodigoHistoriaClinica(String codigoHistoriaClinica)
    {
        this.codigoHistoriaClinica = codigoHistoriaClinica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Odontograma");
        getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odontograma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Odontograma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
