/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import DP.*;

/**
 *
 * @author Alienware
 */
public class PanelFondo extends javax.swing.JPanel {

    private JFrame jFramePadre;
   
    public PanelFondo() {
        initComponents();
        this.setSize(200, 200);
    }
    
    public void paintComponent(Graphics g){
        //Dimension tamanio = getSize();        
        ImageIcon imagenFondo = new ImageIcon(getClass().getResource("diente.jpg"));
        g.drawImage(imagenFondo.getImage(), 0, 0,getWidth(), getHeight(), null);
        setOpaque(false);
        
        super.paintComponent(g);
        repaint();
    }
    
    public JFrame getjFramePadre() {
        return jFramePadre;
    }

    public void setjFramePadre(JFrame jFramePadre) {
        this.jFramePadre = jFramePadre;
    }
    
    public int getCaraA()
    {
        int caraA = 0;
        if(guiCaraA.isSelected())
            caraA = 1;
        return caraA;
    }
    
    public int getCaraB()
    {
        int caraB = 0;
        if(guiCaraB.isSelected())
            caraB = 1;
        return caraB;
    }
    
    public int getCaraC()
    {
        int caraC = 0;
        if(guiCaraC.isSelected())
            caraC = 1;
        return caraC;
    }
    
    public int getCaraD()
    {
        int caraD = 0;
        if(guiCaraD.isSelected())
            caraD = 1;
        return caraD;
    }
    
    public int getCaraE()
    {
        int caraE = 0;
        if(guiCaraE.isSelected())
            caraE = 1;
        return caraE;
    }
    
    public void setCaraA(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraA.setSelected(false);
        else
            guiCaraA.setSelected(true);
    }
    
    public void setCaraB(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraB.setSelected(false);
        else
            guiCaraB.setSelected(true);
    }
    
    public void setCaraC(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraC.setSelected(false);
        else
            guiCaraC.setSelected(true);
    }
    
    public void setCaraD(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraD.setSelected(false);
        else
            guiCaraD.setSelected(true);
    }
    
    public void setCaraE(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraE.setSelected(false);
        else
            guiCaraE.setSelected(true);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guiCaraA = new javax.swing.JRadioButton();
        guiCaraB = new javax.swing.JRadioButton();
        guiCaraE = new javax.swing.JRadioButton();
        guiCaraD = new javax.swing.JRadioButton();
        guiCaraC = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guiCaraD)
                    .addComponent(guiCaraA)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guiCaraB)
                        .addGap(41, 41, 41)
                        .addComponent(guiCaraE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(guiCaraC)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(guiCaraA)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(guiCaraE)
                    .addComponent(guiCaraB)
                    .addComponent(guiCaraC))
                .addGap(36, 36, 36)
                .addComponent(guiCaraD)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton guiCaraA;
    private javax.swing.JRadioButton guiCaraB;
    private javax.swing.JRadioButton guiCaraC;
    private javax.swing.JRadioButton guiCaraD;
    private javax.swing.JRadioButton guiCaraE;
    // End of variables declaration//GEN-END:variables
}
