/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import DP.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Alienware
 */
public class VentanaPaciente extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPaciente
     */
    public VentanaPaciente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        guiCodigoPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        guiClaveNoPaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        guiNombrePaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guiApellidoPaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        guiFechaNacimientoPaciente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        guiEmpresaPaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        guiTelefonoPaciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        guiOcupacionPaciente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        botonIngresarPaciente = new javax.swing.JButton();
        botonActualizarPaciente = new javax.swing.JButton();
        botonEliminarPaciente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de pacientes");
        getContentPane().setLayout(new java.awt.BorderLayout(0, 10));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.GridLayout(8, 2));

        jLabel1.setText("Codigo paciente: ");
        jPanel2.add(jLabel1);

        guiCodigoPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                guiCodigoPacienteFocusLost(evt);
            }
        });
        guiCodigoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiCodigoPacienteActionPerformed(evt);
            }
        });
        jPanel2.add(guiCodigoPaciente);

        jLabel2.setText("Clave No. paciente:");
        jPanel2.add(jLabel2);
        jPanel2.add(guiClaveNoPaciente);

        jLabel3.setText("Nombre paciente:");
        jPanel2.add(jLabel3);
        jPanel2.add(guiNombrePaciente);

        jLabel4.setText("Apellido paciente:");
        jPanel2.add(jLabel4);
        jPanel2.add(guiApellidoPaciente);

        jLabel5.setText("Fecha nacimiento paciente:");
        jPanel2.add(jLabel5);
        jPanel2.add(guiFechaNacimientoPaciente);

        jLabel6.setText("Empresa paciente:");
        jPanel2.add(jLabel6);
        jPanel2.add(guiEmpresaPaciente);

        jLabel7.setText("Teléfono paciente:");
        jPanel2.add(jLabel7);
        jPanel2.add(guiTelefonoPaciente);

        jLabel8.setText("Ocupación paciente:");
        jPanel2.add(jLabel8);
        jPanel2.add(guiOcupacionPaciente);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        botonIngresarPaciente.setText("Ingresar");
        botonIngresarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonIngresarPaciente);

        botonActualizarPaciente.setText("Actualizar");
        botonActualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonActualizarPaciente);

        botonEliminarPaciente.setText("Eliminar");
        botonEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarPaciente);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Paciente pacienteTMP;
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    String fechaTMP;
    java.sql.Date fechaSQL;
    java.util.Date fechaJava;
    
    private void guiCodigoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiCodigoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiCodigoPacienteActionPerformed

    private void botonIngresarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarPacienteActionPerformed
        
        fechaTMP = guiFechaNacimientoPaciente.getText();
        try{
        fechaJava = formato.parse(fechaTMP);
        fechaSQL = new java.sql.Date(fechaJava.getTime());
                        System.out.println(fechaTMP.toString());
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        
       pacienteTMP = new Paciente(guiCodigoPaciente.getText(),guiClaveNoPaciente.getText(),guiNombrePaciente.getText(),
       guiApellidoPaciente.getText(),fechaSQL,guiEmpresaPaciente.getText(),guiTelefonoPaciente.getText(),guiOcupacionPaciente.getText());
         
       try {
            pacienteTMP.ingresarPaciente();
            
            guiCodigoPaciente.setText("");
            guiClaveNoPaciente.setText("");
            guiNombrePaciente.setText("");
            guiApellidoPaciente.setText("");
            guiFechaNacimientoPaciente.setText("");
            guiEmpresaPaciente.setText("");
            guiTelefonoPaciente.setText("");
            guiOcupacionPaciente.setText("");
            
         } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_botonIngresarPacienteActionPerformed

    private void botonEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPacienteActionPerformed
       pacienteTMP = new Paciente(guiCodigoPaciente.getText());
       
       try {
            pacienteTMP.eliminarPaciente();
            
            guiCodigoPaciente.setText("");
            guiClaveNoPaciente.setText("");
            guiNombrePaciente.setText("");
            guiApellidoPaciente.setText("");
            guiFechaNacimientoPaciente.setText("");
            guiEmpresaPaciente.setText("");
            guiTelefonoPaciente.setText("");
            guiOcupacionPaciente.setText("");
            
         } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_botonEliminarPacienteActionPerformed

    private void botonActualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarPacienteActionPerformed
        fechaTMP = guiFechaNacimientoPaciente.getText();
        try{
        fechaJava = formato.parse(fechaTMP);
        fechaSQL = new java.sql.Date(fechaJava.getTime());
                        System.out.println(fechaTMP.toString());
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        
       pacienteTMP = new Paciente(guiCodigoPaciente.getText(),guiClaveNoPaciente.getText(),guiNombrePaciente.getText(),
       guiApellidoPaciente.getText(),fechaSQL,guiEmpresaPaciente.getText(),guiTelefonoPaciente.getText(),guiOcupacionPaciente.getText());
       try {
            pacienteTMP.actualizarPaciente();
            
            guiCodigoPaciente.setText("");
            guiClaveNoPaciente.setText("");
            guiNombrePaciente.setText("");
            guiApellidoPaciente.setText("");
            guiFechaNacimientoPaciente.setText("");
            guiEmpresaPaciente.setText("");
            guiTelefonoPaciente.setText("");
            guiOcupacionPaciente.setText("");
            
         } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_botonActualizarPacienteActionPerformed

    private void guiCodigoPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_guiCodigoPacienteFocusLost
       pacienteTMP = new Paciente(guiCodigoPaciente.getText());
       try{
           if(!(guiCodigoPaciente.getText().equals("")))
           {
                if(pacienteTMP.verificarCodigoPaciente())
                     {
                        botonEliminarPaciente.setEnabled(true);
                        botonActualizarPaciente.setEnabled(true);
                        botonIngresarPaciente.setEnabled(false);

                        pacienteTMP = pacienteTMP.consultarPaciente();

                        guiClaveNoPaciente.setText(pacienteTMP.getClaveNoPaciente());
                        guiNombrePaciente.setText(pacienteTMP.getNombrePaciente());
                        guiApellidoPaciente.setText(pacienteTMP.getApellidoPaciente());
                        guiFechaNacimientoPaciente.setText(""+pacienteTMP.getFechaNacimientoPaciente());
                        guiEmpresaPaciente.setText(pacienteTMP.getEmpresaPaciente());
                        guiTelefonoPaciente.setText(pacienteTMP.getTelefonoPaciente());
                        guiOcupacionPaciente.setText(pacienteTMP.getOcupacionPaciente());
                    }
                else
                     {
                        botonIngresarPaciente.setEnabled(true);
                        botonEliminarPaciente.setEnabled(false);
                        botonActualizarPaciente.setEnabled(false);

                        guiClaveNoPaciente.setText("");
                        guiNombrePaciente.setText("");
                        guiApellidoPaciente.setText("");
                        guiFechaNacimientoPaciente.setText("");
                        guiEmpresaPaciente.setText("");
                        guiTelefonoPaciente.setText("");
                        guiOcupacionPaciente.setText("");

                     }
           }
           else
           {
                botonIngresarPaciente.setEnabled(true);
                botonEliminarPaciente.setEnabled(false);
                botonActualizarPaciente.setEnabled(false);

                guiClaveNoPaciente.setText("");
                guiNombrePaciente.setText("");
                guiApellidoPaciente.setText("");
                guiFechaNacimientoPaciente.setText("");
                guiEmpresaPaciente.setText("");
                guiTelefonoPaciente.setText("");
                guiOcupacionPaciente.setText("");
           }
       } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_guiCodigoPacienteFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarPaciente;
    private javax.swing.JButton botonEliminarPaciente;
    private javax.swing.JButton botonIngresarPaciente;
    private javax.swing.JTextField guiApellidoPaciente;
    private javax.swing.JTextField guiClaveNoPaciente;
    private javax.swing.JTextField guiCodigoPaciente;
    private javax.swing.JTextField guiEmpresaPaciente;
    private javax.swing.JTextField guiFechaNacimientoPaciente;
    private javax.swing.JTextField guiNombrePaciente;
    private javax.swing.JTextField guiOcupacionPaciente;
    private javax.swing.JTextField guiTelefonoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
