/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import DP.*;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alienware
 */
public class VentanaDiente extends javax.swing.JFrame {

    private String codigoHistoriaClinica;
    private Diente dienteTMP = new Diente();
    private ArrayList<Diente> dientes = new ArrayList<Diente>();

    public VentanaDiente() {
        initComponents();
        guiFechaDiente.setEditable(false);
    }
    
    public void setDatos(String codigoHistoriaClinica)
    {
        this.codigoHistoriaClinica = codigoHistoriaClinica;
    }
    
    public void setCodigoHistoriaClinica(String codigoHistoriaClinica)
    {
        this.codigoHistoriaClinica = codigoHistoriaClinica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDientes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        guiFechaDiente = new javax.swing.JTextField();
        piezaDental = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        guiTratamientoDiente = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        guiDiagnosticoDiente = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        guiCaraA = new javax.swing.JRadioButton();
        guiCaraB = new javax.swing.JRadioButton();
        guiCaraC = new javax.swing.JRadioButton();
        guiCaraD = new javax.swing.JRadioButton();
        guiCaraE = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        botonAtctualizarDiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Piezas dentales");
        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(1060, 580));
        setMinimumSize(new java.awt.Dimension(1060, 580));
        setPreferredSize(new java.awt.Dimension(1060, 580));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setText("Tratamiento:");

        tablaDientes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tablaDientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "P.D.", "Diagnostico", "Tratamiento", "Fecha revision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDientes.getTableHeader().setReorderingAllowed(false);
        tablaDientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tablaDientesComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDientes);

        jLabel4.setText("Fecha última revisión:");

        piezaDental.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- -", "11", "12", "13", "14", "15", "16", "17", "18", "21", "22", "23", "24", "25", "26", "27", "28", "31", "32", "33", "34", "35", "36", "37", "38", "41", "42", "43", "44", "45", "46", "47", "48", "51", "52", "53", "54", "55", "61", "62", "63", "64", "65", "71", "72", "73", "74", "75", "81", "82", "83", "84", "85" }));
        piezaDental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                piezaDentalItemStateChanged(evt);
            }
        });
        piezaDental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piezaDentalActionPerformed(evt);
            }
        });

        jLabel1.setText("Pieza dental:");

        jLabel2.setText("Diagnóstico:");

        guiTratamientoDiente.setColumns(20);
        guiTratamientoDiente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        guiTratamientoDiente.setRows(5);
        jScrollPane2.setViewportView(guiTratamientoDiente);

        guiDiagnosticoDiente.setColumns(20);
        guiDiagnosticoDiente.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        guiDiagnosticoDiente.setRows(5);
        jScrollPane3.setViewportView(guiDiagnosticoDiente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(piezaDental, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(guiFechaDiente))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(68, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(piezaDental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiFechaDiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(96, 96, 96)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/diente.JPG"))); // NOI18N

        jLabel6.setText("Pieza dental");

        guiCaraA.setText("A");

        guiCaraB.setText("B");

        guiCaraC.setText("C");

        guiCaraD.setText("D");

        guiCaraE.setText("E");

        jLabel7.setText("Caras afectadas:");

        botonAtctualizarDiente.setText("Actualizar");
        botonAtctualizarDiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtctualizarDienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guiCaraA)
                                .addGap(18, 18, 18)
                                .addComponent(guiCaraB)
                                .addGap(18, 18, 18)
                                .addComponent(guiCaraC)
                                .addGap(18, 18, 18)
                                .addComponent(guiCaraD)
                                .addGap(18, 18, 18)
                                .addComponent(guiCaraE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(botonAtctualizarDiente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guiCaraA)
                    .addComponent(guiCaraB)
                    .addComponent(guiCaraC)
                    .addComponent(guiCaraD)
                    .addComponent(guiCaraE))
                .addGap(34, 34, 34)
                .addComponent(botonAtctualizarDiente)
                .addContainerGap(113, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public int getCaraA()
    {
        int caraA = 0;
        if(guiCaraA.isSelected())
            caraA = 1;
        return caraA;
    }
    
    public int getCaraB()
    {
        int caraB = 0;
        if(guiCaraB.isSelected())
            caraB = 1;
        return caraB;
    }
    
    public int getCaraC()
    {
        int caraC = 0;
        if(guiCaraC.isSelected())
            caraC = 1;
        return caraC;
    }
    
    public int getCaraD()
    {
        int caraD = 0;
        if(guiCaraD.isSelected())
            caraD = 1;
        return caraD;
    }
    
    public int getCaraE()
    {
        int caraE = 0;
        if(guiCaraE.isSelected())
            caraE = 1;
        return caraE;
    }
    
    public void setCaraA(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraA.setSelected(false);
        else
            guiCaraA.setSelected(true);
    }
    
    public void setCaraB(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraB.setSelected(false);
        else
            guiCaraB.setSelected(true);
    }
    
    public void setCaraC(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraC.setSelected(false);
        else
            guiCaraC.setSelected(true);
    }
    
    public void setCaraD(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraD.setSelected(false);
        else
            guiCaraD.setSelected(true);
    }
    
    public void setCaraE(int seleccionado)
    {
        if(seleccionado==0)
            guiCaraE.setSelected(false);
        else
            guiCaraE.setSelected(true);
    }
    
    public void setDatosTablaDientes()
    {
        DefaultTableModel modelo = (DefaultTableModel) tablaDientes.getModel();
        modelo.setRowCount(0);
        dienteTMP = new Diente(this.codigoHistoriaClinica);
        try {
            dientes = dienteTMP.consultarDientes();  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaDiente.class.getName()).log(Level.SEVERE, null, ex);
        }
            for(int i=0;i<dientes.size();i++)
            {
                modelo.addRow(new Object[]{dientes.get(i).getIndiceDiente(),dientes.get(i).getDiagnosticoDiente(),
                    dientes.get(i).getTratamientoDiente(),dientes.get(i).getFechaRevisionDiente()});
            }
    }
    
    private void piezaDentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piezaDentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piezaDentalActionPerformed

    
    private void piezaDentalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_piezaDentalItemStateChanged
        String indiceAux = ""+piezaDental.getSelectedItem();
        dienteTMP = new Diente(codigoHistoriaClinica,indiceAux);
        try 
        {
            if(dienteTMP.verificarDiente())
            {
                dienteTMP = dienteTMP.consultarDiente();
                guiFechaDiente.setText(""+dienteTMP.getFechaRevisionDiente());
                guiDiagnosticoDiente.setText(dienteTMP.getDiagnosticoDiente());
                guiTratamientoDiente.setText(dienteTMP.getTratamientoDiente());
                setCaraA(dienteTMP.getCaraA());
                setCaraB(dienteTMP.getCaraB());
                setCaraC(dienteTMP.getCaraC());
                setCaraD(dienteTMP.getCaraD());
                setCaraE(dienteTMP.getCaraE());
            }
            else
            {
                guiFechaDiente.setText("");
                guiDiagnosticoDiente.setText("");
                guiTratamientoDiente.setText("");
                setCaraA(0);
                setCaraB(0);
                setCaraC(0);
                setCaraD(0);
                setCaraE(0);
            }
        }catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
        }
    }//GEN-LAST:event_piezaDentalItemStateChanged

    private void tablaDientesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tablaDientesComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaDientesComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void botonAtctualizarDienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtctualizarDienteActionPerformed
        dienteTMP = new Diente(codigoHistoriaClinica,""+piezaDental.getSelectedItem());
        java.util.Date fechaJava = new Date();
        java.sql.Date fechaSQL = new java.sql.Date(fechaJava.getTime());
        try {
            if(dienteTMP.verificarDiente())
            {
                dienteTMP.setCodigoHistoriaClinica(codigoHistoriaClinica);
                dienteTMP.setIndiceDiente(""+piezaDental.getSelectedItem());
                dienteTMP.setDiagnosticoDiente(guiDiagnosticoDiente.getText());
                dienteTMP.setTratamientoDiente(guiTratamientoDiente.getText());
                dienteTMP.setFechaRevisionDiente(fechaSQL);
                dienteTMP.setCaraA(getCaraA());
                dienteTMP.setCaraB(getCaraB());
                dienteTMP.setCaraC(getCaraC());
                dienteTMP.setCaraD(getCaraD());
                dienteTMP.setCaraE(getCaraE());

                dienteTMP.actualizarDiente();
                guiFechaDiente.setText(""+fechaSQL);
                this.setDatosTablaDientes();
            }
            else
            {
                dienteTMP.setCodigoHistoriaClinica(codigoHistoriaClinica);
                dienteTMP.setIndiceDiente(""+piezaDental.getSelectedItem());
                dienteTMP.setDiagnosticoDiente(guiDiagnosticoDiente.getText());
                dienteTMP.setTratamientoDiente(guiTratamientoDiente.getText());
                dienteTMP.setFechaRevisionDiente(fechaSQL);
                dienteTMP.setCaraA(getCaraA());
                dienteTMP.setCaraB(getCaraB());
                dienteTMP.setCaraC(getCaraC());
                dienteTMP.setCaraD(getCaraD());
                dienteTMP.setCaraE(getCaraE());

                dienteTMP.ingresarDiente();
                guiFechaDiente.setText(""+fechaSQL);
                this.setDatosTablaDientes();
            }
        }
        catch (ClassNotFoundException ex){
            throw new ClassCastException(ex.getMessage());
        }
    }//GEN-LAST:event_botonAtctualizarDienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDiente().setVisible(true);               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtctualizarDiente;
    private javax.swing.JRadioButton guiCaraA;
    private javax.swing.JRadioButton guiCaraB;
    private javax.swing.JRadioButton guiCaraC;
    private javax.swing.JRadioButton guiCaraD;
    private javax.swing.JRadioButton guiCaraE;
    private javax.swing.JTextArea guiDiagnosticoDiente;
    private javax.swing.JTextField guiFechaDiente;
    private javax.swing.JTextArea guiTratamientoDiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox piezaDental;
    private javax.swing.JTable tablaDientes;
    // End of variables declaration//GEN-END:variables
}
