/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DP.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Alienware
 */
public class VentanaHistoriaClinica extends javax.swing.JFrame {

    /**
     * Creates new form VentanaHistoriaClinica
     */
    
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        java.sql.Date fechaSQL;
        java.util.Date fechaJava;
    
    public VentanaHistoriaClinica() {
        initComponents();
        hcClaveNoPaciente.setEditable(false);
        hcNombrePaciente.setEditable(false);
        hcApellidoPaciente.setEditable(false);
        hcEmpresaPaciente.setEditable(false);
        hcTelefonoPaciente.setEditable(false);
        hcFechaNacimientoPaciente.setEditable(false);
        guiFechaHistoriaClinica.setEditable(false);
        hcOcupacionPaciente.setEditable(false);
        grupoP7.add(guiP72);
        grupoP7.add(guiP73);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupoP7 = new javax.swing.ButtonGroup();
        panelMedio = new javax.swing.JPanel();
        panelIzquierda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        guiP1 = new javax.swing.JRadioButton();
        guiP2 = new javax.swing.JRadioButton();
        guiP3 = new javax.swing.JRadioButton();
        guiP4 = new javax.swing.JRadioButton();
        guiP5 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        guiP121 = new javax.swing.JRadioButton();
        guiP126 = new javax.swing.JRadioButton();
        guiP122 = new javax.swing.JRadioButton();
        guiP124 = new javax.swing.JRadioButton();
        guiP123 = new javax.swing.JRadioButton();
        guiP125 = new javax.swing.JRadioButton();
        guiP127 = new javax.swing.JRadioButton();
        guiP128 = new javax.swing.JRadioButton();
        guiP129 = new javax.swing.JRadioButton();
        guiP120 = new javax.swing.JRadioButton();
        guiP1Texto = new javax.swing.JTextField();
        guiP2Texto = new javax.swing.JTextField();
        guiP3Texto = new javax.swing.JTextField();
        guiP71 = new javax.swing.JRadioButton();
        guiP8 = new javax.swing.JRadioButton();
        guiP9 = new javax.swing.JRadioButton();
        guiP10 = new javax.swing.JRadioButton();
        guiP11 = new javax.swing.JRadioButton();
        guiP13 = new javax.swing.JRadioButton();
        guiP14 = new javax.swing.JRadioButton();
        guiP15 = new javax.swing.JRadioButton();
        guiP16 = new javax.swing.JRadioButton();
        guiP61 = new javax.swing.JRadioButton();
        guiP62 = new javax.swing.JRadioButton();
        guiP63 = new javax.swing.JRadioButton();
        guiP72 = new javax.swing.JRadioButton();
        guiP73 = new javax.swing.JRadioButton();
        guiP11Texto = new javax.swing.JTextField();
        panelDerecha = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        guiP171 = new javax.swing.JRadioButton();
        guiP172 = new javax.swing.JRadioButton();
        guiP173 = new javax.swing.JRadioButton();
        guiP175 = new javax.swing.JRadioButton();
        guiP177 = new javax.swing.JRadioButton();
        guiP176 = new javax.swing.JRadioButton();
        guiP174 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        guiP20 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        guiP211 = new javax.swing.JRadioButton();
        guiP215 = new javax.swing.JRadioButton();
        guiP212 = new javax.swing.JRadioButton();
        guiP216 = new javax.swing.JRadioButton();
        guiP213 = new javax.swing.JRadioButton();
        guiP217 = new javax.swing.JRadioButton();
        guiP214 = new javax.swing.JRadioButton();
        guiP218 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        guiP221 = new javax.swing.JRadioButton();
        guiP223 = new javax.swing.JRadioButton();
        guiP222 = new javax.swing.JRadioButton();
        guiP224 = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        guiP23 = new javax.swing.JTextArea();
        guiP19 = new javax.swing.JTextField();
        guiP18 = new javax.swing.JTextField();
        panelArriba = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        hcCodigoPaciente = new javax.swing.JTextField();
        hcNombrePaciente = new javax.swing.JTextField();
        hcClaveNoPaciente = new javax.swing.JTextField();
        hcApellidoPaciente = new javax.swing.JTextField();
        hcFechaNacimientoPaciente = new javax.swing.JTextField();
        hcTelefonoPaciente = new javax.swing.JTextField();
        hcEmpresaPaciente = new javax.swing.JTextField();
        hcOcupacionPaciente = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        hcCodigoUsuario = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        guiFechaHistoriaClinica = new javax.swing.JTextField();
        panelAbajo = new javax.swing.JPanel();
        botonIngresarHistoriaClinica = new javax.swing.JButton();
        botonEliminarHistoriaClinica = new javax.swing.JButton();
        botonActualizarHistoriaClinica = new javax.swing.JButton();
        botonModificarPiezas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de historias clínicas");
        setMinimumSize(new java.awt.Dimension(1011, 680));
        setPreferredSize(new java.awt.Dimension(1011, 680));

        panelMedio.setBackground(new java.awt.Color(204, 204, 204));
        panelMedio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMedio.setForeground(new java.awt.Color(204, 204, 204));
        panelMedio.setMinimumSize(new java.awt.Dimension(930, 477));
        panelMedio.setPreferredSize(new java.awt.Dimension(930, 246));
        panelMedio.setLayout(new java.awt.GridBagLayout());

        panelIzquierda.setBackground(new java.awt.Color(204, 204, 204));
        panelIzquierda.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("1. Está usted bajo tratamiento médico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("2.Toma actualmente algún medicamento?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("3. Le han practicado alguna intervención quirúrgica?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("4. Ha recibido alguna transfución sanguínea?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("5. Ha consumido o consume drogas?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("6. Ha presentado agluna reacción alérgica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("7. Sufre de tensión arterial?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("8. Sangra excesivamente al cortarse?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("9. Padece de algún problema sanguíneo?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("10. Es Ud. VIH+ ?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel10, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setText("11.Toma algún medicamento retroviral?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel11, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("12. Sufre o ha sufrido de:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel12, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setText("13. Está Ud. embarazada?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("14. Está actualmente tomando pastillas anticonceptivas?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("15. Ha tenido limitaciones al abrir o cerrar la boca?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel15, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("16. Siente ruidos en la mandíbula al abrir o cerrar la boca?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel16, gridBagConstraints);

        guiP1.setBackground(new java.awt.Color(204, 204, 204));
        guiP1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP1.setText("Si");
        guiP1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guiP1StateChanged(evt);
            }
        });
        guiP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiP1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP1, gridBagConstraints);

        guiP2.setBackground(new java.awt.Color(204, 204, 204));
        guiP2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP2.setText("Si");
        guiP2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guiP2StateChanged(evt);
            }
        });
        guiP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiP2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP2, gridBagConstraints);

        guiP3.setBackground(new java.awt.Color(204, 204, 204));
        guiP3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP3.setText("Si");
        guiP3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guiP3StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP3, gridBagConstraints);

        guiP4.setBackground(new java.awt.Color(204, 204, 204));
        guiP4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP4.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP4, gridBagConstraints);

        guiP5.setBackground(new java.awt.Color(204, 204, 204));
        guiP5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP5.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP5, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setText("    a los siguientes medicamentos?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(jLabel17, gridBagConstraints);

        guiP121.setBackground(new java.awt.Color(204, 204, 204));
        guiP121.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP121.setText("Enfermedades venéreas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP121, gridBagConstraints);

        guiP126.setBackground(new java.awt.Color(204, 204, 204));
        guiP126.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP126.setText("Fiebre reumática");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP126, gridBagConstraints);

        guiP122.setBackground(new java.awt.Color(204, 204, 204));
        guiP122.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP122.setText("Problemas cardíacos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP122, gridBagConstraints);

        guiP124.setBackground(new java.awt.Color(204, 204, 204));
        guiP124.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP124.setText("Hepatitis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP124, gridBagConstraints);

        guiP123.setBackground(new java.awt.Color(204, 204, 204));
        guiP123.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP123.setText("Tuberculosis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP123, gridBagConstraints);

        guiP125.setBackground(new java.awt.Color(204, 204, 204));
        guiP125.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP125.setText("Problemas hepáticos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP125, gridBagConstraints);

        guiP127.setBackground(new java.awt.Color(204, 204, 204));
        guiP127.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP127.setText("Asma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP127, gridBagConstraints);

        guiP128.setBackground(new java.awt.Color(204, 204, 204));
        guiP128.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP128.setText("Diabetes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP128, gridBagConstraints);

        guiP129.setBackground(new java.awt.Color(204, 204, 204));
        guiP129.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP129.setText("Úlcera gástrica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP129, gridBagConstraints);

        guiP120.setBackground(new java.awt.Color(204, 204, 204));
        guiP120.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP120.setText("Tiroides");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP120, gridBagConstraints);

        guiP1Texto.setColumns(200);
        guiP1Texto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP1Texto.setEnabled(false);
        guiP1Texto.setMinimumSize(new java.awt.Dimension(150, 19));
        guiP1Texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiP1TextoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        panelIzquierda.add(guiP1Texto, gridBagConstraints);

        guiP2Texto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP2Texto.setEnabled(false);
        guiP2Texto.setMinimumSize(new java.awt.Dimension(150, 19));
        guiP2Texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiP2TextoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        panelIzquierda.add(guiP2Texto, gridBagConstraints);

        guiP3Texto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP3Texto.setEnabled(false);
        guiP3Texto.setMinimumSize(new java.awt.Dimension(150, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        panelIzquierda.add(guiP3Texto, gridBagConstraints);

        guiP71.setBackground(new java.awt.Color(204, 204, 204));
        guiP71.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP71.setText("Si");
        guiP71.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guiP71StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP71, gridBagConstraints);

        guiP8.setBackground(new java.awt.Color(204, 204, 204));
        guiP8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP8.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP8, gridBagConstraints);

        guiP9.setBackground(new java.awt.Color(204, 204, 204));
        guiP9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP9.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP9, gridBagConstraints);

        guiP10.setBackground(new java.awt.Color(204, 204, 204));
        guiP10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP10.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP10, gridBagConstraints);

        guiP11.setBackground(new java.awt.Color(204, 204, 204));
        guiP11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP11.setText("Si");
        guiP11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                guiP11StateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP11, gridBagConstraints);

        guiP13.setBackground(new java.awt.Color(204, 204, 204));
        guiP13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP13.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP13, gridBagConstraints);

        guiP14.setBackground(new java.awt.Color(204, 204, 204));
        guiP14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP14.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP14, gridBagConstraints);

        guiP15.setBackground(new java.awt.Color(204, 204, 204));
        guiP15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP15.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP15, gridBagConstraints);

        guiP16.setBackground(new java.awt.Color(204, 204, 204));
        guiP16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP16.setText("Si");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP16, gridBagConstraints);

        guiP61.setBackground(new java.awt.Color(204, 204, 204));
        guiP61.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP61.setText("Penicilina");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP61, gridBagConstraints);

        guiP62.setBackground(new java.awt.Color(204, 204, 204));
        guiP62.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP62.setText("Anestesia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP62, gridBagConstraints);

        guiP63.setBackground(new java.awt.Color(204, 204, 204));
        guiP63.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP63.setText("Aspirina, yodo, etc");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP63, gridBagConstraints);

        guiP72.setBackground(new java.awt.Color(204, 204, 204));
        guiP72.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP72.setText("Alta");
        guiP72.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelIzquierda.add(guiP72, gridBagConstraints);

        guiP73.setBackground(new java.awt.Color(204, 204, 204));
        guiP73.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP73.setText("Baja");
        guiP73.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelIzquierda.add(guiP73, gridBagConstraints);

        guiP11Texto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP11Texto.setEnabled(false);
        guiP11Texto.setMinimumSize(new java.awt.Dimension(150, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        panelIzquierda.add(guiP11Texto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 33);
        panelMedio.add(panelIzquierda, gridBagConstraints);

        panelDerecha.setBackground(new java.awt.Color(204, 204, 204));
        panelDerecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelDerecha.setLayout(new java.awt.GridBagLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setText("17. Presenta alguno de los siguientes hábitos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(jLabel18, gridBagConstraints);

        guiP171.setBackground(new java.awt.Color(204, 204, 204));
        guiP171.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP171.setText("Se muerde las uñas o los labios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        panelDerecha.add(guiP171, gridBagConstraints);

        guiP172.setBackground(new java.awt.Color(204, 204, 204));
        guiP172.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP172.setText("Fuma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        panelDerecha.add(guiP172, gridBagConstraints);

        guiP173.setBackground(new java.awt.Color(204, 204, 204));
        guiP173.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP173.setText("Respiración bucal");
        guiP173.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiP173ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        panelDerecha.add(guiP173, gridBagConstraints);

        guiP175.setBackground(new java.awt.Color(204, 204, 204));
        guiP175.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP175.setText("Consume alimentos cítricos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP175, gridBagConstraints);

        guiP177.setBackground(new java.awt.Color(204, 204, 204));
        guiP177.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP177.setText("Muerde objetos con los dientes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP177, gridBagConstraints);

        guiP176.setBackground(new java.awt.Color(204, 204, 204));
        guiP176.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP176.setText("Consume picante");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP176, gridBagConstraints);

        guiP174.setBackground(new java.awt.Color(204, 204, 204));
        guiP174.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP174.setText("Sufre herpes labial o aftas recurrentes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 16);
        panelDerecha.add(guiP174, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel19.setText("18. Motivo de la enfermedad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(jLabel19, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setText("19. Enfermedad actual:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(jLabel20, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setText("20. Evolución clínica de la enfermedad:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(jLabel21, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 80));

        guiP20.setColumns(20);
        guiP20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP20.setRows(5);
        jScrollPane1.setViewportView(guiP20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        panelDerecha.add(jScrollPane1, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("21. Exámen clínico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(jLabel22, gridBagConstraints);

        guiP211.setBackground(new java.awt.Color(204, 204, 204));
        guiP211.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP211.setText("Labios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 46, 0, 46);
        panelDerecha.add(guiP211, gridBagConstraints);

        guiP215.setBackground(new java.awt.Color(204, 204, 204));
        guiP215.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP215.setText("Mucosa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP215, gridBagConstraints);

        guiP212.setBackground(new java.awt.Color(204, 204, 204));
        guiP212.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP212.setText("Lengua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 46, 0, 46);
        panelDerecha.add(guiP212, gridBagConstraints);

        guiP216.setBackground(new java.awt.Color(204, 204, 204));
        guiP216.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP216.setText("Paladar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP216, gridBagConstraints);

        guiP213.setBackground(new java.awt.Color(204, 204, 204));
        guiP213.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP213.setText("Cigarrillos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 46, 0, 46);
        panelDerecha.add(guiP213, gridBagConstraints);

        guiP217.setBackground(new java.awt.Color(204, 204, 204));
        guiP217.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP217.setText("Encías");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP217, gridBagConstraints);

        guiP214.setBackground(new java.awt.Color(204, 204, 204));
        guiP214.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP214.setText("Ganglios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 46, 0, 46);
        panelDerecha.add(guiP214, gridBagConstraints);

        guiP218.setBackground(new java.awt.Color(204, 204, 204));
        guiP218.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP218.setText("A.T.M.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP218, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel23.setText("22. Exámenes complementarios:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(jLabel23, gridBagConstraints);

        guiP221.setBackground(new java.awt.Color(204, 204, 204));
        guiP221.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP221.setText("Radiográficos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 47, 0, 47);
        panelDerecha.add(guiP221, gridBagConstraints);

        guiP223.setBackground(new java.awt.Color(204, 204, 204));
        guiP223.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP223.setText("Modelos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP223, gridBagConstraints);

        guiP222.setBackground(new java.awt.Color(204, 204, 204));
        guiP222.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP222.setText("Laboratorio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 47, 0, 47);
        panelDerecha.add(guiP222, gridBagConstraints);

        guiP224.setBackground(new java.awt.Color(204, 204, 204));
        guiP224.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP224.setText("Tensión arterial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP224, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setText("23. Observaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(jLabel24, gridBagConstraints);

        jScrollPane2.setMinimumSize(new java.awt.Dimension(200, 80));

        guiP23.setColumns(20);
        guiP23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP23.setRows(5);
        jScrollPane2.setViewportView(guiP23);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 2;
        panelDerecha.add(jScrollPane2, gridBagConstraints);

        guiP19.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP19.setMinimumSize(new java.awt.Dimension(150, 19));
        guiP19.setPreferredSize(new java.awt.Dimension(150, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelDerecha.add(guiP19, gridBagConstraints);

        guiP18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiP18.setMinimumSize(new java.awt.Dimension(150, 19));
        guiP18.setPreferredSize(new java.awt.Dimension(150, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelDerecha.add(guiP18, gridBagConstraints);

        panelMedio.add(panelDerecha, new java.awt.GridBagConstraints());

        getContentPane().add(panelMedio, java.awt.BorderLayout.CENTER);

        panelArriba.setBackground(new java.awt.Color(204, 204, 204));
        panelArriba.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelArriba.setLayout(new java.awt.GridBagLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setText("Código paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        panelArriba.add(jLabel25, gridBagConstraints);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel26.setText("Clave No. paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelArriba.add(jLabel26, gridBagConstraints);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel27.setText("Nombre paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(jLabel27, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel28.setText("Teléfono paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(jLabel28, gridBagConstraints);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel29.setText("Apellido paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(jLabel29, gridBagConstraints);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel30.setText("Ocupación paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(jLabel30, gridBagConstraints);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel31.setText("Empresa paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(jLabel31, gridBagConstraints);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel32.setText("Fecha de nacimiento paciente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(jLabel32, gridBagConstraints);

        hcCodigoPaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hcCodigoPaciente.setMinimumSize(new java.awt.Dimension(120, 19));
        hcCodigoPaciente.setPreferredSize(new java.awt.Dimension(120, 19));
        hcCodigoPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcCodigoPacienteFocusLost(evt);
            }
        });
        hcCodigoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcCodigoPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(hcCodigoPaciente, gridBagConstraints);

        hcNombrePaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hcNombrePaciente.setMinimumSize(new java.awt.Dimension(120, 19));
        hcNombrePaciente.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(hcNombrePaciente, gridBagConstraints);

        hcClaveNoPaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hcClaveNoPaciente.setMinimumSize(new java.awt.Dimension(120, 19));
        hcClaveNoPaciente.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(hcClaveNoPaciente, gridBagConstraints);

        hcApellidoPaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hcApellidoPaciente.setMinimumSize(new java.awt.Dimension(120, 19));
        hcApellidoPaciente.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(hcApellidoPaciente, gridBagConstraints);

        hcFechaNacimientoPaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hcFechaNacimientoPaciente.setMinimumSize(new java.awt.Dimension(120, 19));
        hcFechaNacimientoPaciente.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(hcFechaNacimientoPaciente, gridBagConstraints);

        hcTelefonoPaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hcTelefonoPaciente.setMinimumSize(new java.awt.Dimension(120, 19));
        hcTelefonoPaciente.setPreferredSize(new java.awt.Dimension(120, 19));
        hcTelefonoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcTelefonoPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(hcTelefonoPaciente, gridBagConstraints);

        hcEmpresaPaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hcEmpresaPaciente.setMinimumSize(new java.awt.Dimension(120, 19));
        hcEmpresaPaciente.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(hcEmpresaPaciente, gridBagConstraints);

        hcOcupacionPaciente.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hcOcupacionPaciente.setMinimumSize(new java.awt.Dimension(120, 19));
        hcOcupacionPaciente.setPreferredSize(new java.awt.Dimension(120, 19));
        hcOcupacionPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hcOcupacionPacienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelArriba.add(hcOcupacionPaciente, gridBagConstraints);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel33.setText("INFORMACIÓN DEL PACIENTE: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 18;
        panelArriba.add(jLabel33, gridBagConstraints);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel35.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        panelArriba.add(jLabel35, gridBagConstraints);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel36.setText("Código usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelArriba.add(jLabel36, gridBagConstraints);

        hcCodigoUsuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        hcCodigoUsuario.setEnabled(false);
        hcCodigoUsuario.setMinimumSize(new java.awt.Dimension(120, 19));
        hcCodigoUsuario.setPreferredSize(new java.awt.Dimension(120, 19));
        hcCodigoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hcCodigoUsuarioFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        panelArriba.add(hcCodigoUsuario, gridBagConstraints);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel34.setText("Fecha última revisión:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        panelArriba.add(jLabel34, gridBagConstraints);

        guiFechaHistoriaClinica.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        guiFechaHistoriaClinica.setMinimumSize(new java.awt.Dimension(120, 19));
        guiFechaHistoriaClinica.setPreferredSize(new java.awt.Dimension(120, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 3;
        panelArriba.add(guiFechaHistoriaClinica, gridBagConstraints);

        getContentPane().add(panelArriba, java.awt.BorderLayout.PAGE_START);

        panelAbajo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelAbajo.setLayout(new java.awt.GridLayout(1, 0));

        botonIngresarHistoriaClinica.setBackground(new java.awt.Color(255, 255, 255));
        botonIngresarHistoriaClinica.setText("Ingresar");
        botonIngresarHistoriaClinica.setEnabled(false);
        botonIngresarHistoriaClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarHistoriaClinicaActionPerformed(evt);
            }
        });
        panelAbajo.add(botonIngresarHistoriaClinica);

        botonEliminarHistoriaClinica.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminarHistoriaClinica.setText("Eliminar");
        botonEliminarHistoriaClinica.setEnabled(false);
        botonEliminarHistoriaClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarHistoriaClinicaActionPerformed(evt);
            }
        });
        panelAbajo.add(botonEliminarHistoriaClinica);

        botonActualizarHistoriaClinica.setBackground(new java.awt.Color(255, 255, 255));
        botonActualizarHistoriaClinica.setText("Actualizar");
        botonActualizarHistoriaClinica.setEnabled(false);
        botonActualizarHistoriaClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarHistoriaClinicaActionPerformed(evt);
            }
        });
        panelAbajo.add(botonActualizarHistoriaClinica);

        botonModificarPiezas.setBackground(new java.awt.Color(255, 255, 255));
        botonModificarPiezas.setText("Piezas dentales");
        botonModificarPiezas.setEnabled(false);
        botonModificarPiezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPiezasActionPerformed(evt);
            }
        });
        panelAbajo.add(botonModificarPiezas);

        getContentPane().add(panelAbajo, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        HistoriaClinica historiaClinicaTMP;
    
    private void guiP1TextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiP1TextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiP1TextoActionPerformed

    private void guiP2TextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiP2TextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiP2TextoActionPerformed

    private void guiP173ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiP173ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiP173ActionPerformed

    private void hcTelefonoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcTelefonoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcTelefonoPacienteActionPerformed

    private void hcOcupacionPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcOcupacionPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcOcupacionPacienteActionPerformed

    private void guiP1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guiP1StateChanged
       
        if(guiP1.isSelected())
            guiP1Texto.setEnabled(true);
        else
        {
            guiP1Texto.setEnabled(false);
            guiP1Texto.setText("");
        }
    }//GEN-LAST:event_guiP1StateChanged

    private void guiP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiP1ActionPerformed

    private void guiP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiP2ActionPerformed

    private void guiP2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guiP2StateChanged
        if(guiP2.isSelected())
            guiP2Texto.setEnabled(true);
        else
        {
            guiP2Texto.setEnabled(false);
            guiP2Texto.setText("");
        }
    }//GEN-LAST:event_guiP2StateChanged

    private void guiP3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guiP3StateChanged
        if(guiP3.isSelected())
            guiP3Texto.setEnabled(true);
        else
        {
            guiP3Texto.setEnabled(false);
            guiP3Texto.setText("");
        }
    }//GEN-LAST:event_guiP3StateChanged

    private void guiP11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guiP11StateChanged
       if(guiP11.isSelected())
            guiP11Texto.setEnabled(true);
        else
        {
            guiP11Texto.setEnabled(false);
            guiP11Texto.setText("");
        }
    }//GEN-LAST:event_guiP11StateChanged

    private void hcCodigoPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcCodigoPacienteFocusLost
       Paciente pacienteTMP = new Paciente(hcCodigoPaciente.getText());
       try{
           if(!(hcCodigoPaciente.getText().equals("")))
           {
                if(pacienteTMP.verificarCodigoPaciente())
                     {
                 pacienteTMP = pacienteTMP.consultarPaciente();

                        hcClaveNoPaciente.setText(pacienteTMP.getClaveNoPaciente());
                        hcNombrePaciente.setText(pacienteTMP.getNombrePaciente());
                        hcApellidoPaciente.setText(pacienteTMP.getApellidoPaciente());
                        hcFechaNacimientoPaciente.setText(""+pacienteTMP.getFechaNacimientoPaciente());
                        hcEmpresaPaciente.setText(pacienteTMP.getEmpresaPaciente());
                        hcTelefonoPaciente.setText(pacienteTMP.getTelefonoPaciente());
                        hcOcupacionPaciente.setText(pacienteTMP.getOcupacionPaciente());
                        
                        hcCodigoUsuario.setEnabled(true);
                    }
                else
                     {
                        hcClaveNoPaciente.setText("");
                        hcNombrePaciente.setText("");
                        hcApellidoPaciente.setText("");
                        hcFechaNacimientoPaciente.setText("");
                        hcEmpresaPaciente.setText("");
                        hcTelefonoPaciente.setText("");
                        hcOcupacionPaciente.setText("");
                        
                        hcCodigoUsuario.setEnabled(false);
                        hcCodigoUsuario.setText("");

                     }
           }
           else
           {
                hcClaveNoPaciente.setText("");
                hcNombrePaciente.setText("");
                hcApellidoPaciente.setText("");
                hcFechaNacimientoPaciente.setText("");
                hcEmpresaPaciente.setText("");
                hcTelefonoPaciente.setText("");
                hcOcupacionPaciente.setText("");

                hcCodigoUsuario.setEnabled(false);
                hcCodigoUsuario.setText("");
           }
       } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_hcCodigoPacienteFocusLost

    private void botonIngresarHistoriaClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarHistoriaClinicaActionPerformed

        String P1="",P2="",P3="",P6="",P7="",P11="",P12="",P17="",P18="",P19="",P20="",P21="",P22="",P23="";
        int P4=0,P5=0,P8=0,P9=0,P10=0,P13=0,P14=0,P15=0,P16=0;
        fechaJava = new Date();
        fechaSQL = new java.sql.Date(fechaJava.getTime());
       JRadioButton [] arregloP6 = {guiP61,guiP62,guiP63};
       JRadioButton [] arregloP12 = {guiP121,guiP122,guiP123,guiP124,guiP125,guiP126,guiP127,guiP128,guiP129,guiP120};
       JRadioButton [] arregloP17 = {guiP171,guiP172,guiP173,guiP174,guiP175,guiP176,guiP177};
       JRadioButton [] arregloP21 = {guiP211,guiP212,guiP213,guiP214,guiP215,guiP216,guiP217,guiP218};
       JRadioButton [] arregloP22 = {guiP221,guiP222,guiP223,guiP224};
       
       String codigoHC = hcCodigoPaciente.getText()+""+hcCodigoUsuario.getText();
       
       if(guiP1.isSelected())
           P1 = "true;"+guiP1Texto.getText();
       else
           P1 = "false";
       if(guiP2.isSelected())
           P2 = "true;"+guiP2Texto.getText();
       else
           P2 = "false";
       if(guiP3.isSelected())
           P3 = "true;"+guiP3Texto.getText();
       else
           P3 = "false";
       if(guiP4.isSelected())
           P4 = 1;
       if(guiP5.isSelected())
           P5 = 1;
       for(int i = 0; i<arregloP6.length;i++)
       {
           if(arregloP6[i].isSelected())
               P6 = P6+arregloP6[i].getText()+".;";
           else
               P6 = P6+".;";
       }
       if(guiP71.isSelected())
       {
           if(guiP72.isSelected())
               P7=P7+guiP72.getText();
           else if(guiP73.isSelected())
               P7=P7+guiP73.getText();
       }
       if(guiP8.isSelected())
           P8 = 1;
       if(guiP9.isSelected())
           P9 = 1;
       if(guiP10.isSelected())
           P10 = 1;
       if(guiP11.isSelected())
           P11 = "true;"+guiP11Texto.getText();
       else
           P11 = "false";
       for(int i = 0; i<arregloP12.length;i++)
       {
           if(arregloP12[i].isSelected())
               P12 = P12+arregloP12[i].getText()+".;";
           else
               P12 = P12+".;";
       }
       if(guiP13.isSelected())
           P13 = 1;
       if(guiP14.isSelected())
           P14 = 1;
       if(guiP15.isSelected())
           P15 = 1;
       if(guiP16.isSelected())
           P16 = 1;
       for(int i = 0; i<arregloP17.length;i++)
       {
           if(arregloP17[i].isSelected())
               P17 = P17+arregloP17[i].getText()+".;";
           else
               P17 = P17+".;";
       }
       P18 = guiP18.getText();
       P19 = guiP19.getText();
       P20 = guiP20.getText();
       for(int i = 0; i<arregloP21.length;i++)
       {
           if(arregloP21[i].isSelected())
               P21 = P21+arregloP21[i].getText()+".;";
           else
               P21 = P21+".;";
       }
       for(int i = 0; i<arregloP22.length;i++)
       {
           if(arregloP22[i].isSelected())
               P22 = P22+arregloP22[i].getText()+".;";
           else
               P22 = P22+".;";
       }
       P23 = guiP20.getText();
        
       historiaClinicaTMP = new HistoriaClinica(codigoHC,hcCodigoPaciente.getText(),hcCodigoUsuario.getText(),fechaSQL,P1,P2,P3,P4,P5,
               P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23);
         
        try{
            historiaClinicaTMP.ingresarHistoriaClinica();

            
         } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
        
                                                      
    }//GEN-LAST:event_botonIngresarHistoriaClinicaActionPerformed

    private void guiP71StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_guiP71StateChanged
        if(guiP71.isSelected())
        {
            guiP72.setEnabled(true);
            guiP73.setEnabled(true);
        }
        else
        {
            guiP72.setEnabled(false);
            guiP73.setEnabled(false);
            
        }
    }//GEN-LAST:event_guiP71StateChanged

    private void hcCodigoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hcCodigoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hcCodigoPacienteActionPerformed

    private void botonEliminarHistoriaClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarHistoriaClinicaActionPerformed
       String codigoHC = hcCodigoPaciente.getText()+""+hcCodigoUsuario.getText();
       JRadioButton [] arregloP6 = {guiP61,guiP62,guiP63};
       JRadioButton [] arregloP12 = {guiP121,guiP122,guiP123,guiP124,guiP125,guiP126,guiP127,guiP128,guiP129,guiP120};
       JRadioButton [] arregloP17 = {guiP171,guiP172,guiP173,guiP174,guiP175,guiP176,guiP177};
       JRadioButton [] arregloP21 = {guiP211,guiP212,guiP213,guiP214,guiP215,guiP216,guiP217,guiP218};
       JRadioButton [] arregloP22 = {guiP221,guiP222,guiP223,guiP224};
       JRadioButton [] arregloPResto = {guiP1,guiP2,guiP3,guiP4,guiP5,guiP8,guiP9,guiP10,guiP11,guiP13,guiP14,guiP15,guiP16};
       JTextField [] arregloTexto = {guiP1Texto,guiP2Texto,guiP3Texto,guiP11Texto,guiP18,guiP19};
       JTextArea [] arregloAreas = {guiP20,guiP23};
       
       historiaClinicaTMP = new HistoriaClinica(codigoHC);
         
       try {
            historiaClinicaTMP.elminarHistoriaClinica();
            
            hcCodigoPaciente.setText("");
            hcClaveNoPaciente.setText("");
            hcNombrePaciente.setText("");
            hcApellidoPaciente.setText("");
            hcFechaNacimientoPaciente.setText("");
            hcEmpresaPaciente.setText("");
            hcTelefonoPaciente.setText("");
            hcOcupacionPaciente.setText("");    
            
            for(int i = 0; i<arregloP6.length;i++)
                arregloP6[i].setSelected(false);
            for(int i = 0; i<arregloP12.length;i++)
                arregloP12[i].setSelected(false);
            for(int i = 0; i<arregloP17.length;i++)
                arregloP17[i].setSelected(false);
            for(int i = 0; i<arregloP21.length;i++)
                arregloP21[i].setSelected(false);
            for(int i = 0; i<arregloP22.length;i++)
                arregloP22[i].setSelected(false);  
            for(int i = 0; i<arregloPResto.length;i++)
                arregloPResto[i].setSelected(false);
            for(int i = 0; i<arregloTexto.length;i++)
                arregloTexto[i].setText("");
            for(int i = 0; i<arregloAreas.length;i++)
                arregloAreas[i].setText("");
            
            botonModificarPiezas.setEnabled(false);
            botonIngresarHistoriaClinica.setEnabled(false);
            botonEliminarHistoriaClinica.setEnabled(false);
            botonActualizarHistoriaClinica.setEnabled(false);

         } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_botonEliminarHistoriaClinicaActionPerformed

    private void botonActualizarHistoriaClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarHistoriaClinicaActionPerformed
        String P1="",P2="",P3="",P6="",P7="",P11="",P12="",P17="",P18="",P19="",P20="",P21="",P22="",P23="";
        int P4=0,P5=0,P8=0,P9=0,P10=0,P13=0,P14=0,P15=0,P16=0;
        fechaJava = new Date();
        fechaSQL = new java.sql.Date(fechaJava.getTime());

       JRadioButton [] arregloP6 = {guiP61,guiP62,guiP63};
       JRadioButton [] arregloP12 = {guiP121,guiP122,guiP123,guiP124,guiP125,guiP126,guiP127,guiP128,guiP129,guiP120};
       JRadioButton [] arregloP17 = {guiP171,guiP172,guiP173,guiP174,guiP175,guiP176,guiP177};
       JRadioButton [] arregloP21 = {guiP211,guiP212,guiP213,guiP214,guiP215,guiP216,guiP217,guiP218};
       JRadioButton [] arregloP22 = {guiP221,guiP222,guiP223,guiP224};
       
       String codigoHC = hcCodigoPaciente.getText()+""+hcCodigoUsuario.getText();
       
       if(guiP1.isSelected())
           P1 = "true;"+guiP1Texto.getText();
       else
           P1 = "false";
       if(guiP2.isSelected())
           P2 = "true;"+guiP2Texto.getText();
       else
           P2 = "false";
       if(guiP3.isSelected())
           P3 = "true;"+guiP3Texto.getText();
       else
           P3 = "false";
       if(guiP4.isSelected())
           P4 = 1;
       if(guiP5.isSelected())
           P5 = 1;
       for(int i = 0; i<arregloP6.length;i++)
       {
           if(arregloP6[i].isSelected())
               P6 = P6+arregloP6[i].getText()+".;";
           else
               P6 = P6+".;";
       }
       if(guiP71.isSelected())
       {
           if(guiP72.isSelected())
               P7=P7+guiP72.getText();
           else if(guiP73.isSelected())
               P7=P7+guiP73.getText();
       }
       if(guiP8.isSelected())
           P8 = 1;
       if(guiP9.isSelected())
           P9 = 1;
       if(guiP10.isSelected())
           P10 = 1;
       if(guiP11.isSelected())
           P11 = "true;"+guiP11Texto.getText();
       else
           P11 = "false";
       for(int i = 0; i<arregloP12.length;i++)
       {
           if(arregloP12[i].isSelected())
               P12 = P12+arregloP12[i].getText()+".;";
           else
               P12 = P12+".;";
       }
       if(guiP13.isSelected())
           P13 = 1;
       if(guiP14.isSelected())
           P14 = 1;
       if(guiP15.isSelected())
           P15 = 1;
       if(guiP16.isSelected())
           P16 = 1;
       for(int i = 0; i<arregloP17.length;i++)
       {
           if(arregloP17[i].isSelected())
               P17 = P17+arregloP17[i].getText()+".;";
           else
               P17 = P17+".;";
       }
       P18 = guiP18.getText();
       P19 = guiP19.getText();
       P20 = guiP20.getText();
       for(int i = 0; i<arregloP21.length;i++)
       {
           if(arregloP21[i].isSelected())
               P21 = P21+arregloP21[i].getText()+".;";
           else
               P21 = P21+".;";
       }
       for(int i = 0; i<arregloP22.length;i++)
       {
           if(arregloP22[i].isSelected())
               P22 = P22+arregloP22[i].getText()+".;";
           else
               P22 = P22+".;";
       }
       P23 = guiP23.getText();
 
        
       historiaClinicaTMP = new HistoriaClinica(codigoHC,hcCodigoPaciente.getText(),hcCodigoUsuario.getText(),fechaSQL,P1,P2,P3,P4,P5,
               P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23);
         
        try{
            historiaClinicaTMP.actualizarHistoriaClinica();
            
            /*guiCodigoPaciente.setText("");
            guiClaveNoPaciente.setText("");
            guiNombrePaciente.setText("");
            guiApellidoPaciente.setText("");
            guiFechaNacimientoPaciente.setText("");
            guiEmpresaPaciente.setText("");
            guiTelefonoPaciente.setText("");
            guiOcupacionPaciente.setText("");*/
            
         } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_botonActualizarHistoriaClinicaActionPerformed

    private void hcCodigoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hcCodigoUsuarioFocusLost
       String codigoHC = hcCodigoPaciente.getText()+""+hcCodigoUsuario.getText();
       historiaClinicaTMP = new HistoriaClinica(codigoHC);
       try{
           if(!(codigoHC.equals("")))
           {
                if(historiaClinicaTMP.verificarCodigoHistoriaClinica())
                     {
                        botonModificarPiezas.setEnabled(true);
                        botonIngresarHistoriaClinica.setEnabled(false);
                        botonEliminarHistoriaClinica.setEnabled(true);
                        botonActualizarHistoriaClinica.setEnabled(true);
                        historiaClinicaTMP = historiaClinicaTMP.consultarHistoriaClinica();
                        guiFechaHistoriaClinica.setText(""+historiaClinicaTMP.getFechaHistoriaClinica());
                        String strAux =  historiaClinicaTMP.getP1();
                        String [] arrayAux = strAux.split(";");
                        //1
                        if(arrayAux.length>1)
                        {
                            guiP1.setSelected(true);
                            guiP1Texto.setText(arrayAux[1]);
                        }
                        else
                        {
                            guiP1.setSelected(false);
                            guiP1Texto.setText("");                                        
                        }
                        //2
                        strAux =  historiaClinicaTMP.getP2();
                        arrayAux = strAux.split(";");
                        if(arrayAux.length>1)
                        {
                            guiP2.setSelected(true);
                            guiP2Texto.setText(arrayAux[1]);
                        }
                        else
                        {
                            guiP2.setSelected(false);
                            guiP2Texto.setText("");                                        
                        }
                        //3
                        strAux =  historiaClinicaTMP.getP3();
                        arrayAux = strAux.split(";");
                        if(arrayAux.length>1)
                        {
                            guiP3.setSelected(true);
                            guiP3Texto.setText(arrayAux[1]);
                        }
                        else
                        {
                            guiP3.setSelected(false);
                            guiP3Texto.setText("");                                        
                        }
                        //11
                        strAux =  historiaClinicaTMP.getP11();
                        arrayAux = strAux.split(";");
                        if(arrayAux.length>1)
                        {
                            guiP11.setSelected(true);
                            guiP11Texto.setText(arrayAux[1]);
                        }
                        else
                        {
                            guiP11.setSelected(false);
                            guiP11Texto.setText("");                                        
                        }
                       //4
                        if(historiaClinicaTMP.getP4()==0)
                            guiP4.setSelected(false);
                        else
                            guiP4.setSelected(true);
                        //5
                        if(historiaClinicaTMP.getP5()==0)
                            guiP5.setSelected(false);
                        else
                            guiP5.setSelected(true);
                        //8
                        if(historiaClinicaTMP.getP8()==0)
                            guiP8.setSelected(false);
                        else
                            guiP8.setSelected(true);
                        //9
                        if(historiaClinicaTMP.getP9()==0)
                            guiP9.setSelected(false);
                        else
                            guiP9.setSelected(true);
                        //10
                        if(historiaClinicaTMP.getP10()==0)
                            guiP10.setSelected(false);
                        else
                            guiP10.setSelected(true);
                        //13
                        if(historiaClinicaTMP.getP13()==0)
                            guiP13.setSelected(false);
                        else
                            guiP13.setSelected(true);
                        //14
                        if(historiaClinicaTMP.getP14()==0)
                            guiP14.setSelected(false);
                        else
                            guiP14.setSelected(true);
                        //15
                        if(historiaClinicaTMP.getP15()==0)
                            guiP15.setSelected(false);
                        else
                            guiP15.setSelected(true);
                        //16
                        if(historiaClinicaTMP.getP16()==0)
                            guiP16.setSelected(false);
                        else
                            guiP16.setSelected(true);
                        //6
                        strAux =  historiaClinicaTMP.getP6();
                        arrayAux = strAux.split(";");
                        JRadioButton [] arregloP6 = {guiP61,guiP62,guiP63};
                        for(int i = 0;i<arrayAux.length;i++)
                        {
                            if(arrayAux[i].equals("."))
                                arregloP6[i].setSelected(false);
                            else
                                arregloP6[i].setSelected(true);
                        }
                        //12
                        strAux =  historiaClinicaTMP.getP12();
                        arrayAux = strAux.split(";");
                        JRadioButton [] arregloP12 = {guiP121,guiP122,guiP123,guiP124,guiP125,guiP126,guiP127,guiP128,guiP129,guiP120};
                        for(int i = 0;i<arrayAux.length;i++)
                        {
                            if(arrayAux[i].equals("."))
                                arregloP12[i].setSelected(false);
                            else
                                arregloP12[i].setSelected(true);
                        }
                        //17
                        strAux =  historiaClinicaTMP.getP17();
                        arrayAux = strAux.split(";");
                        JRadioButton [] arregloP17 = {guiP171,guiP172,guiP173,guiP174,guiP175,guiP176,guiP177};
                        for(int i = 0;i<arrayAux.length;i++)
                        {
                            if(arrayAux[i].equals("."))
                                arregloP17[i].setSelected(false);
                            else
                                arregloP17[i].setSelected(true);
                        }
                        //21
                        strAux =  historiaClinicaTMP.getP21();
                        arrayAux = strAux.split(";");
                        JRadioButton [] arregloP21 = {guiP211,guiP212,guiP213,guiP214,guiP215,guiP216,guiP217,guiP218};
                        for(int i = 0;i<arrayAux.length;i++)
                        {
                            if(arrayAux[i].equals("."))
                                arregloP21[i].setSelected(false);
                            else
                                arregloP21[i].setSelected(true);
                        }
                         //21
                        strAux =  historiaClinicaTMP.getP22();
                        arrayAux = strAux.split(";");
                        JRadioButton [] arregloP22 = {guiP221,guiP222,guiP223,guiP224};
                        for(int i = 0;i<arrayAux.length;i++)
                        {
                            if(arrayAux[i].equals("."))
                                arregloP22[i].setSelected(false);
                            else
                                arregloP22[i].setSelected(true);
                        }
                        //18,19
                        String [] arrayTexto = {historiaClinicaTMP.getP18(),historiaClinicaTMP.getP19()};
                        JTextField [] arregloTexto = {guiP18,guiP19};
                        for(int i = 0;i<arrayTexto.length;i++)
                                arregloTexto[i].setText(arrayTexto[i]);
                        //20,23
                        String [] arrayAreas = {historiaClinicaTMP.getP20(),historiaClinicaTMP.getP23()};
                        JTextArea [] arregloAreas = {guiP20,guiP23};
                        for(int i = 0;i<arrayAreas.length;i++)
                                arregloAreas[i].setText(arrayAreas[i]);
                        //7
                        strAux = historiaClinicaTMP.getP7();
                        if(!(strAux.equals("")))
                        {
                            guiP71.setSelected(true);
                            if(strAux.equals("Alta"))
                                guiP72.setSelected(true);                            
                            else if(strAux.equals("Baja"))
                                guiP73.setSelected(true);
                        }
                        else
                            guiP71.setSelected(false);
                        
                       
                    }
                else
                     {
                       botonModificarPiezas.setEnabled(false);
                       botonIngresarHistoriaClinica.setEnabled(true);
                       botonEliminarHistoriaClinica.setEnabled(false);
                       botonActualizarHistoriaClinica.setEnabled(false);
                     }
           }
       }
       catch (ClassNotFoundException ex) {
       throw new ClassCastException(ex.getMessage());
       }
            
    }//GEN-LAST:event_hcCodigoUsuarioFocusLost

    private void botonModificarPiezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPiezasActionPerformed
        String codigoHC = hcCodigoPaciente.getText()+""+hcCodigoUsuario.getText();
     
        VentanaDiente ventanaDiente = new VentanaDiente();
        ventanaDiente.setCodigoHistoriaClinica(codigoHC);
        ventanaDiente.setDatosTablaDientes();
        ventanaDiente.setVisible(true);
    }//GEN-LAST:event_botonModificarPiezasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaHistoriaClinica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarHistoriaClinica;
    private javax.swing.JButton botonEliminarHistoriaClinica;
    private javax.swing.JButton botonIngresarHistoriaClinica;
    private javax.swing.JButton botonModificarPiezas;
    private javax.swing.ButtonGroup grupoP7;
    private javax.swing.JTextField guiFechaHistoriaClinica;
    private javax.swing.JRadioButton guiP1;
    private javax.swing.JRadioButton guiP10;
    private javax.swing.JRadioButton guiP11;
    private javax.swing.JTextField guiP11Texto;
    private javax.swing.JRadioButton guiP120;
    private javax.swing.JRadioButton guiP121;
    private javax.swing.JRadioButton guiP122;
    private javax.swing.JRadioButton guiP123;
    private javax.swing.JRadioButton guiP124;
    private javax.swing.JRadioButton guiP125;
    private javax.swing.JRadioButton guiP126;
    private javax.swing.JRadioButton guiP127;
    private javax.swing.JRadioButton guiP128;
    private javax.swing.JRadioButton guiP129;
    private javax.swing.JRadioButton guiP13;
    private javax.swing.JRadioButton guiP14;
    private javax.swing.JRadioButton guiP15;
    private javax.swing.JRadioButton guiP16;
    private javax.swing.JRadioButton guiP171;
    private javax.swing.JRadioButton guiP172;
    private javax.swing.JRadioButton guiP173;
    private javax.swing.JRadioButton guiP174;
    private javax.swing.JRadioButton guiP175;
    private javax.swing.JRadioButton guiP176;
    private javax.swing.JRadioButton guiP177;
    private javax.swing.JTextField guiP18;
    private javax.swing.JTextField guiP19;
    private javax.swing.JTextField guiP1Texto;
    private javax.swing.JRadioButton guiP2;
    private javax.swing.JTextArea guiP20;
    private javax.swing.JRadioButton guiP211;
    private javax.swing.JRadioButton guiP212;
    private javax.swing.JRadioButton guiP213;
    private javax.swing.JRadioButton guiP214;
    private javax.swing.JRadioButton guiP215;
    private javax.swing.JRadioButton guiP216;
    private javax.swing.JRadioButton guiP217;
    private javax.swing.JRadioButton guiP218;
    private javax.swing.JRadioButton guiP221;
    private javax.swing.JRadioButton guiP222;
    private javax.swing.JRadioButton guiP223;
    private javax.swing.JRadioButton guiP224;
    private javax.swing.JTextArea guiP23;
    private javax.swing.JTextField guiP2Texto;
    private javax.swing.JRadioButton guiP3;
    private javax.swing.JTextField guiP3Texto;
    private javax.swing.JRadioButton guiP4;
    private javax.swing.JRadioButton guiP5;
    private javax.swing.JRadioButton guiP61;
    private javax.swing.JRadioButton guiP62;
    private javax.swing.JRadioButton guiP63;
    private javax.swing.JRadioButton guiP71;
    private javax.swing.JRadioButton guiP72;
    private javax.swing.JRadioButton guiP73;
    private javax.swing.JRadioButton guiP8;
    private javax.swing.JRadioButton guiP9;
    private javax.swing.JTextField hcApellidoPaciente;
    private javax.swing.JTextField hcClaveNoPaciente;
    private javax.swing.JTextField hcCodigoPaciente;
    private javax.swing.JTextField hcCodigoUsuario;
    private javax.swing.JTextField hcEmpresaPaciente;
    private javax.swing.JTextField hcFechaNacimientoPaciente;
    private javax.swing.JTextField hcNombrePaciente;
    private javax.swing.JTextField hcOcupacionPaciente;
    private javax.swing.JTextField hcTelefonoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelAbajo;
    private javax.swing.JPanel panelArriba;
    private javax.swing.JPanel panelDerecha;
    private javax.swing.JPanel panelIzquierda;
    private javax.swing.JPanel panelMedio;
    // End of variables declaration//GEN-END:variables
}
