/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;
import DP.*;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author Alienware
 */
public class VentanaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaUsuario
     */
    public VentanaUsuario() {
        initComponents();
        botonIngresarUsuario.setEnabled(false);
        botonEliminarUsuario.setEnabled(false);
        botonActualizarUsuario.setEnabled(false);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        botonIngresarUsuario = new javax.swing.JButton();
        botonEliminarUsuario = new javax.swing.JButton();
        botonActualizarUsuario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        guiCodigoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        guiNombreUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        guiApellidoUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        guiEspecialidadUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        guiCelularUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        guiDireccionUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        botonIngresarUsuario.setText("Ingresar");
        botonIngresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(botonIngresarUsuario);

        botonEliminarUsuario.setText("Eliminar");
        botonEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(botonEliminarUsuario);

        botonActualizarUsuario.setText("Actualizar");
        botonActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(botonActualizarUsuario);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(6, 2));

        jLabel1.setText("Código usuario:");
        jPanel1.add(jLabel1);

        guiCodigoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                guiCodigoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                guiCodigoUsuarioFocusLost(evt);
            }
        });
        guiCodigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiCodigoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(guiCodigoUsuario);

        jLabel2.setText("Nombre usuario:");
        jPanel1.add(jLabel2);
        jPanel1.add(guiNombreUsuario);

        jLabel3.setText("Apellido usuario:");
        jPanel1.add(jLabel3);
        jPanel1.add(guiApellidoUsuario);

        jLabel4.setText("Especialidad usuario:");
        jPanel1.add(jLabel4);
        jPanel1.add(guiEspecialidadUsuario);

        jLabel5.setText("Celular usuario:");
        jPanel1.add(jLabel5);
        jPanel1.add(guiCelularUsuario);

        jLabel6.setText("Dirección usuario:");
        jPanel1.add(jLabel6);
        jPanel1.add(guiDireccionUsuario);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     Usuario usuarioTMP;
    
    private void guiCodigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiCodigoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guiCodigoUsuarioActionPerformed

    private void botonIngresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarUsuarioActionPerformed
        
       usuarioTMP = new Usuario(guiCodigoUsuario.getText(),guiNombreUsuario.getText(),guiApellidoUsuario.getText(),
       guiEspecialidadUsuario.getText(),guiCelularUsuario.getText(),guiDireccionUsuario.getText());
         
       try {
            usuarioTMP.ingresarUsuario();
            
            guiCodigoUsuario.setText("");
            guiNombreUsuario.setText("");
            guiApellidoUsuario.setText("");
            guiEspecialidadUsuario.setText("");
            guiCelularUsuario.setText("");
            guiDireccionUsuario.setText("");
            
         } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_botonIngresarUsuarioActionPerformed

    private void botonEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUsuarioActionPerformed
        usuarioTMP = new Usuario(guiCodigoUsuario.getText());
         
       try {
            usuarioTMP.eliminarUsuario();
            
            guiCodigoUsuario.setText("");
            guiNombreUsuario.setText("");
            guiApellidoUsuario.setText("");
            guiEspecialidadUsuario.setText("");
            guiCelularUsuario.setText("");
            guiDireccionUsuario.setText("");
            
         } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_botonEliminarUsuarioActionPerformed

    private void botonActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarUsuarioActionPerformed
        usuarioTMP = new Usuario(guiCodigoUsuario.getText(),guiNombreUsuario.getText(),guiApellidoUsuario.getText(),
        guiEspecialidadUsuario.getText(),guiCelularUsuario.getText(),guiDireccionUsuario.getText());
         
       try {
            usuarioTMP.actualizarUsuario();
            
            guiCodigoUsuario.setText("");
            guiNombreUsuario.setText("");
            guiApellidoUsuario.setText("");
            guiEspecialidadUsuario.setText("");
            guiCelularUsuario.setText("");
            guiDireccionUsuario.setText("");
            
         } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_botonActualizarUsuarioActionPerformed

    private void guiCodigoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_guiCodigoUsuarioFocusLost
       usuarioTMP = new Usuario(guiCodigoUsuario.getText());
       try{
            if(usuarioTMP.verificarCodigoUsuario())
                 {
                    botonEliminarUsuario.setEnabled(true);
                    botonActualizarUsuario.setEnabled(true);
                    botonIngresarUsuario.setEnabled(false);
                    
                    usuarioTMP = usuarioTMP.consultarUsuario();
                    
                    guiNombreUsuario.setText(usuarioTMP.getNombreUsuario());
                    guiApellidoUsuario.setText(usuarioTMP.getApellidoUsuario());
                    guiEspecialidadUsuario.setText(usuarioTMP.getEspecialidadUsuario());
                    guiCelularUsuario.setText(usuarioTMP.getCelularUsuario());
                    guiDireccionUsuario.setText(usuarioTMP.getDireccionUsuario());
                         }
            else
                 {
                    botonIngresarUsuario.setEnabled(true);
                    botonEliminarUsuario.setEnabled(false);
                    botonActualizarUsuario.setEnabled(false);
                    
                    guiNombreUsuario.setText("");
                    guiApellidoUsuario.setText("");
                    guiEspecialidadUsuario.setText("");
                    guiCelularUsuario.setText("");
                    guiDireccionUsuario.setText("");
                 }
       } catch (ClassNotFoundException ex) {
            throw new ClassCastException(ex.getMessage());
         }
    }//GEN-LAST:event_guiCodigoUsuarioFocusLost

    private void guiCodigoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_guiCodigoUsuarioFocusGained
          
    }//GEN-LAST:event_guiCodigoUsuarioFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarUsuario;
    private javax.swing.JButton botonEliminarUsuario;
    private javax.swing.JButton botonIngresarUsuario;
    private javax.swing.JTextField guiApellidoUsuario;
    private javax.swing.JTextField guiCelularUsuario;
    private javax.swing.JTextField guiCodigoUsuario;
    private javax.swing.JTextField guiDireccionUsuario;
    private javax.swing.JTextField guiEspecialidadUsuario;
    private javax.swing.JTextField guiNombreUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
